"""Curated mutation nodes with ClinVar and cBioPortal source reconciliation."""

from mtor_nexus.disease.classes import CBIOPORTAL_ER_POSITIVE_PIK3CA
from mtor_nexus.disease.models import FunctionalEffect, MutationRecord, MutationSource
from mtor_nexus.schema import SpeciesEvidence, Tier

HUMAN_GENETICS = [SpeciesEvidence.HUMAN]


def curated_mutations() -> list[MutationRecord]:
    """Return normalized mutation records safe for open redistribution."""

    return [
        MutationRecord(
            mutation_id="MUT:PIK3CA:p.Glu545Lys",
            gene_symbol="PIK3CA",
            hgvs_protein="p.Glu545Lys",
            hgvs_coding="c.1633G>A",
            oncogenicity="oncogenic hotspot",
            functional_effect=FunctionalEffect.ACTIVATING,
            tier=Tier.ROBUST,
            species_evidence=HUMAN_GENETICS,
            sources=[MutationSource.CBIOPORTAL, MutationSource.CURATED],
            source_refs=["cbioportal:brca_tcga:E545K"],
            cancer_frequencies=[CBIOPORTAL_ER_POSITIVE_PIK3CA],
            cosmic_reconciliation="licensed-local-overlay-required",
        ),
        MutationRecord(
            mutation_id="MUT:PIK3CA:p.His1047Arg",
            gene_symbol="PIK3CA",
            hgvs_protein="p.His1047Arg",
            hgvs_coding="c.3140A>G",
            oncogenicity="oncogenic hotspot",
            functional_effect=FunctionalEffect.ACTIVATING,
            tier=Tier.ROBUST,
            species_evidence=HUMAN_GENETICS,
            sources=[MutationSource.CBIOPORTAL, MutationSource.CURATED],
            source_refs=["cbioportal:brca_tcga:H1047R"],
            cancer_frequencies=[CBIOPORTAL_ER_POSITIVE_PIK3CA],
            cosmic_reconciliation="licensed-local-overlay-required",
        ),
        MutationRecord(
            mutation_id="MUT:PTEN:p.Arg130Ter",
            gene_symbol="PTEN",
            hgvs_protein="p.Arg130Ter",
            hgvs_coding="c.388C>T",
            clinical_significance="Pathogenic",
            functional_effect=FunctionalEffect.LOSS_OF_FUNCTION,
            tier=Tier.ROBUST,
            species_evidence=HUMAN_GENETICS,
            sources=[MutationSource.CLINVAR],
            source_refs=["clinvar:VCV000007819.128"],
        ),
        MutationRecord(
            mutation_id="MUT:PTEN:p.Arg233Ter",
            gene_symbol="PTEN",
            hgvs_protein="p.Arg233Ter",
            hgvs_coding="c.697C>T",
            clinical_significance="curated loss-of-function signature",
            functional_effect=FunctionalEffect.LOSS_OF_FUNCTION,
            tier=Tier.ROBUST,
            species_evidence=HUMAN_GENETICS,
            sources=[MutationSource.CURATED],
            source_refs=["curated:PTEN:R233*"],
            cosmic_reconciliation="licensed-local-overlay-required",
        ),
        MutationRecord(
            mutation_id="MUT:AKT1:p.Glu17Lys",
            gene_symbol="AKT1",
            hgvs_protein="p.Glu17Lys",
            hgvs_coding="c.49G>A",
            oncogenicity="oncogenic hotspot",
            functional_effect=FunctionalEffect.ACTIVATING,
            tier=Tier.ROBUST,
            species_evidence=HUMAN_GENETICS,
            sources=[MutationSource.CBIOPORTAL, MutationSource.CURATED],
            source_refs=["cbioportal:pan-cancer:AKT1:E17K"],
            cosmic_reconciliation="licensed-local-overlay-required",
        ),
        MutationRecord(
            mutation_id="MUT:MTOR:p.Met2327Ile",
            gene_symbol="MTOR",
            hgvs_protein="p.Met2327Ile",
            hgvs_coding="c.6981G>A",
            oncogenicity="curated activating signature",
            functional_effect=FunctionalEffect.ACTIVATING,
            tier=Tier.PLAUSIBLE,
            species_evidence=HUMAN_GENETICS,
            sources=[MutationSource.CURATED],
            source_refs=["curated:MTOR:M2327I"],
            cosmic_reconciliation="licensed-local-overlay-required",
        ),
        MutationRecord(
            mutation_id="MUT:MTOR:p.Glu1799Lys",
            gene_symbol="MTOR",
            hgvs_protein="p.Glu1799Lys",
            hgvs_coding="c.5395G>A",
            clinical_significance="Pathogenic",
            functional_effect=FunctionalEffect.ACTIVATING,
            tier=Tier.ROBUST,
            species_evidence=HUMAN_GENETICS,
            sources=[MutationSource.CLINVAR],
            source_refs=["clinvar:VCV000217823.74", "omim:616638"],
        ),
        MutationRecord(
            mutation_id="MUT:TSC1:p.Val831fs",
            gene_symbol="TSC1",
            hgvs_protein="p.Val831fs",
            hgvs_coding="c.2491del",
            clinical_significance="Pathogenic",
            functional_effect=FunctionalEffect.LOSS_OF_FUNCTION,
            tier=Tier.ROBUST,
            species_evidence=HUMAN_GENETICS,
            sources=[MutationSource.CLINVAR],
            source_refs=["clinvar:VCV004852004.1"],
        ),
        MutationRecord(
            mutation_id="MUT:TSC2:p.Thr584fs",
            gene_symbol="TSC2",
            hgvs_protein="p.Thr584fs",
            hgvs_coding="c.1750dup",
            clinical_significance="Pathogenic",
            functional_effect=FunctionalEffect.LOSS_OF_FUNCTION,
            tier=Tier.ROBUST,
            species_evidence=HUMAN_GENETICS,
            sources=[MutationSource.CLINVAR],
            source_refs=["clinvar:VCV004851321.1"],
        ),
        MutationRecord(
            mutation_id="MUT:DEPDC5:p.Gly1014fs",
            gene_symbol="DEPDC5",
            hgvs_protein="p.Gly1014fs",
            hgvs_coding="c.3041del",
            clinical_significance="Likely pathogenic",
            functional_effect=FunctionalEffect.LOSS_OF_FUNCTION,
            tier=Tier.ROBUST,
            species_evidence=HUMAN_GENETICS,
            sources=[MutationSource.CLINVAR],
            source_refs=["clinvar:VCV004845712.1"],
        ),
        MutationRecord(
            mutation_id="MUT:STK11:p.Pro281fs",
            gene_symbol="STK11",
            hgvs_protein="p.Pro281fs",
            hgvs_coding="c.842del",
            clinical_significance="Pathogenic",
            functional_effect=FunctionalEffect.LOSS_OF_FUNCTION,
            tier=Tier.ROBUST,
            species_evidence=HUMAN_GENETICS,
            sources=[MutationSource.CLINVAR],
            source_refs=["clinvar:VCV000192227.17"],
        ),
        MutationRecord(
            mutation_id="MUT:STRADA:c.95-2A>C",
            gene_symbol="STRADA",
            hgvs_protein=None,
            hgvs_coding="c.95-2A>C",
            clinical_significance="Likely pathogenic",
            functional_effect=FunctionalEffect.LOSS_OF_FUNCTION,
            tier=Tier.ROBUST,
            species_evidence=HUMAN_GENETICS,
            sources=[MutationSource.CLINVAR],
            source_refs=["clinvar:VCV004772793.1"],
        ),
    ]
